### ISSUE TITLE
Frequently append data or row to feature dataframes indexed on time

### ISSUE THREAD

**Issue by sharabhshukla** [bytehub-ai/bytehub#6]
Hi,

I have a use case where time series dataframe needs to be appended with the latest values every 5 minutes, is there a method or an elegant way of appending time series value/row to a feature dataframe very few minutes. One way would be to load the entire dataframe from the featurestore everytime in memory and then append a row and then rewrite the entire dataframe. But I was wondering if there is a method that just appends it or sort of updates it ?

**Comment by toby-coleman** [comment]
Actually you can append data simply by calling `save_dataframe` - there is no need to load the entire dataframe and write back. For example
```python
# Create a feature
fs.create_feature('test/append-dataframe')

# Create some data to put in it
dts = pd.date_range('2021-01-01', '2021-01-02', freq='30min')
df = pd.DataFrame({'time': dts, 'value': list(range(len(dts)))})

# Insert the data into the feature store one row at a time
for row_id in range(len(df)):
    # Save a single row of the dataframe to the feature store
    fs.save_dataframe(df.iloc[row_id:row_id + 1], 'test/append-dataframe')

# Read the data back from the feature store
df_result = fs.load_dataframe('test/append-dataframe')
```

After inserting the data one row at a time, `df_result` will contain the full dataframe. We should probably add an example to the docs covering how to add/append feature data.

**Comment by sharabhshukla** [comment]
Hi, I ma trying to get my setup working on google cloud, I am able to run other lines suucessfully, but when i try saving the dataframe to cloud storage, using fs.save_datframe I run into an error like the one shown below, I checked my google cloud storage functionality by saving the dataframe using . to_parquest by supplying the google cloud storage path gs://{bucketname}/{foldername}

_call non-retriable exception: Disallowed unicode characters present in object name ''tutorial/feature/append-dataframe/partition=npartitions=1

**Comment by toby-coleman** [comment]
Added tutorial to cover this use-case: https://docs.bytehub.ai/tutorials/saving-appending-data
